.TH newsbaoter 1 "January 2015" "newsbaoter 0.1" "User Commands"
.SH NAME
newsbaoter \- news feed reader
.SH SYNOPSIS
\fBnewsbaoter\fP [\fBoptions\fP]
.SH OPTIONS
.TP
\fB\-d
Output debug information in the log file.
.TP
\fB\-D
Output debug information to stderr.
.SH FILES
.TP
~/.newsbaoter/urls
List of news feed URLs to pull
.TP
~/.newsbaoter/config
General newsbaoter configuration options
.TP
~/.newsbaoter/debug
Debug log file
